# Generated by Django 3.1.7 on 2021-04-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20210428_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='repo_link',
            field=models.CharField(default='#', max_length=1000),
        ),
    ]
