# Generated by Django 3.1.7 on 2021-04-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_portal_repo_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('description', models.CharField(default='nothing has been added here', max_length=1000)),
                ('repo_link', models.CharField(default='#', max_length=1000)),
                ('repo_link2', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='portal',
            name='repo_link2',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
