# Generated by Django 3.1.7 on 2021-04-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20210428_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portal',
            name='Add_repo_link',
        ),
        migrations.RemoveField(
            model_name='script',
            name='Add_repo_link',
        ),
    ]
