# Generated by Django 3.1.7 on 2021-04-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20210428_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal',
            name='repo_link2',
            field=models.CharField(default='NA', max_length=1000),
        ),
        migrations.AlterField(
            model_name='script',
            name='repo_link2',
            field=models.CharField(default='NA', max_length=1000),
        ),
    ]
