# Generated by Django 3.1.7 on 2021-04-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20210428_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='Add_repo_link',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='script',
            name='Add_repo_link',
            field=models.BooleanField(default=0),
        ),
    ]
